[package]
name = "intder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "irreps"
path = "src/bin/irreps.rs"

[dependencies]
approx = "0.5.1"
nalgebra = "0.31.1"
psqs = { git = "https://github.com/ntBre/psqs", rev =  "6568cf5" }
regex = "1.5.5"
symm = { git = "https://github.com/ntBre/symm", rev = "2d523057" }
tensor = { git = "https://github.com/ntBre/tensor", rev = "0d2913e" }
