* Geometry conversion
** B Matrix and s vectors
   See [[pdf:~/Library/McIntosh78.pdf][McIntosh78]] for details on the construction of B matrix
   - in turn it refers to /Molecular Vibrations/, which has been sitting on the floor
     behind me the whole time I was beating my head against the fortran version...

   also see [[https://github.com/psi4/psi3/blob/master/src/bin/intder/README][nate's readme]] from trying to convert it to C++

   I think B does only depend on the simple internals

   B relates the simple internals to the Cartesian coordinates

   This was true, but BS is B converted to symmetry-internal coordinates, and that
   is what is actually used later

   see comments on a_matrix for expression, something like D = BBt and A = BtD-1

   compute A, multiply by the difference between SIC_desired and SIC_current and
   add that step to the Cartesian coordinates

* Force constant conversion
** Fortran code
*** INPFKM - load internal coordinate force constants from file
    - I handle this in =Intder::load=
*** Assemble B matrix
*** BINVRT - get A matrix, just like geometry conversion
*** MACHX
**** Stretch
     - HIJS1
     - AHX2
**** Bend
     - HIJS2
     - AHX3
*** MACHY
**** Stretch
     - HIJKS1
     - HSRY2
     - AHY2
**** Bend
     - HIJKS2
     - HSRY3
     - AHY3
*** LINTR - I expect this to perform the transformations using the matrices from MACHX/Y
*** *can actually stop here* - fc2,3,4 are finished in =LINTR=
*** XF2
*** XF3
*** YF2
*** FCOUT
*** this is where the files are written, then it does the vibrational analysis
**** GFMAT - normal mode analysis in internal coordinates
**** NORMCO - normal mode analysis in cartesian coordinates

* Adding more coordinate types
  So far I have only implemented STRE, BEND, and TORS. The steps for adding more
  are as follows:
  1. Add a new =Siic= variant
  2. Add a new case to =parse_simple_internal=
  3. Follow the compiler to all the places you need to handle the new =Siic=

* Timing
  fairer comparison to DEBUG=true version since that writes something like
  intder.out

  ouch, mine takes longer with 8.8M vs 14.9M lines printed. lines weren't the
  whole story though. my lines are wider so file size is 1.4 GB vs 800 MB for
  mine and the old version, respectively. that explains mine taking longer

  | Molecule  | Old       | New+Debug | New       |
  |-----------+-----------+-----------+-----------|
  | C7H2 Orig | 1m18.593s | 2m2.780s  | 0m26.215s |
  | C7H2 prof |           | 1m51.760s | 0m16.808s |

* TODO make sure NSIC = 0 works
  should make it possible to use just simple internals for Cs molecules, for
  example. this might work if I just loop over symmetry_internals everywhere
  right now, but I'm not sure

* References
  - D. F. McIntosh, K. H. Michaelian, and M. R. Peterson. Can. J. Chem. Vol. 56,
    1978
  - E. B. Wilson, Jr., J. C. Decius, and P. C. Cross. Molecular
    Vibrations, 1955.
  - W. D. Allen and A. G. Csaszar. J. Chem. Phys. 98, 1993.
  - A. L. L. East, W. D. Allen, and S. J. Klippenstein. J. Chem. Phys. 102, 1995

